version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "meetup-crawler-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vz1xbmsw8cna"
s3_prefix = "meetup-crawler"
region = "eu-west-3"
capabilities = "CAPABILITY_IAM"
