AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

# TODO should use parameters for SubnetIds, SecurityGroup, Secret 

Description: >
  meetup-crawler

  Crawls Meetup.com API to retrieve groups data and event details

Globals:
  Function:
    Runtime: python3.8
    Timeout: 30
    Environment:
      Variables:
        PYTHON_LOGLEVEL: "DEBUG"
        DB_SECRET_NAME: "meetupcrawlerdatabaseSecret-IotH2oBYYAAG"
              
Resources:
  MeetupCrawlerFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: meetupcrawler.app.lambda_handler
     
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:eu-west-3:486652066693:secret:meetupcrawlerdatabaseSecret-IotH2oBYYAAG-3CbT5p"
     
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MeetupCodeSqsQueue.Arn
            BatchSize: 10

      VpcConfig:
        SubnetIds: 
          # private subnet from the RDS VPC (with NAT Gateway because we need to call AWS and external APIs)
          # https://stackoverflow.com/questions/52992085/why-cant-an-aws-lambda-function-inside-a-public-subnet-in-a-vpc-connect-to-the
          - "subnet-0eec570f870efe6c3"
          - "subnet-04f464473c5ac812c"
        SecurityGroupIds:
          - "sg-0655a345b3b79c539" # security group authorized to make inbound connections to RDS cluster 
        
  # MeetupMembersFunction:
  #   Type: AWS::Serverless::Function 
  #   Properties:
  #     CodeUri: meetupcrawler/
  #     Handler: meetup.members
          
  MeetupCodeSqsQueue:
    Type: AWS::SQS::Queue
